addr = ":8000"

email_smtp_addr = "smtp.gmail.com:587"
email_from = "user@gmail.com"
email_password = "password"

[users.alice]
email = "alice@example.com"

[[users.alice.filters]]
authors = ["bob@example.com"]
branches = ["master", "gh-pages"]
repos = ["public-repo"]

[users.bob]
email = "bob@example.com"

[[users.bob.filters]]
repos = ["public-repo"]
